name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using this plugin and taking the time to fill out this bug report !
  - type: input
    id: maplibre-react-components-version
    attributes:
      label: maplibre-react-components version
      description: npm list maplibre-react-components
      placeholder: x.y.z
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: your OS, React version
      placeholder: "OS Linux, React 18.3"
      description: Depending on the context choose the most appropriate informations
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        ⚠️  This is the most important part of the report ⚠️
        Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
        Please, take the time to show us some code and/or config that is needed for others to reproduce the problem easily.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: |
        Optional: only if you have suggestions on a fix/reason for the bug
        Don't hesitate to create a pull request with your solution, it helps get faster feedback.
